printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
jsxSingleQuote: false
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
htmlWhitespaceSensitivity: css
endOfLine: lf
