rules:
  ## Possible Errors
  # Color
  color-no-invalid-hex: true

  # Font family
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true

  # Function
  function-calc-no-invalid: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true

  # String
  string-no-newline:

  # Unit
  unit-no-unknown: true

  # Property
  property-no-unknown: true

  # Keyframe declaration
  keyframe-declaration-no-important: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true

  # Block
  block-no-empty: true
  # Selector
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true

  # Media feature
  media-feature-name-no-unknown: true

  # At-rule
  at-rule-no-unknown: true

  # Comment
  comment-no-empty: true

  # General / Sheet
  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true

  ## Limit language features
  # Color
  color-named: null
  color-no-hex: null

  # Function
  #function-blacklist: Specify a blacklist of disallowed functions.
  function-url-no-scheme-relative: null
  #function-url-scheme-blacklist: Specify a blacklist of disallowed URL schemes.
  #function-url-scheme-whitelist: Specify a whitelist of allowed URL schemes.
  #function-whitelist: Specify a whitelist of allowed functions.

  # Keyframes
  #keyframes-name-pattern: Specify a pattern for keyframe names.

  # Number
  #number-max-precision: Limit the number of decimal places allowed in numbers.

  # Time
  #time-min-milliseconds: Specify the minimum number of milliseconds for time values.

  # Unit
  #unit-blacklist: Specify a blacklist of disallowed units.
  #unit-whitelist: Specify a whitelist of allowed units.

  # Shorthand property
  shorthand-property-no-redundant-values: true

  # Value
  value-no-vendor-prefix: null

  # Custom property
  #custom-property-pattern: Specify a pattern for custom properties.

  # Property
  #property-blacklist: Specify a blacklist of disallowed properties.
  property-no-vendor-prefix: null
  #property-whitelist: Specify a whitelist of allowed properties.

  # Declaration
  declaration-block-no-redundant-longhand-properties: true
  declaration-no-important: true
  #declaration-property-unit-blacklist: Specify a blacklist of disallowed property and unit pairs within declarations.
  #declaration-property-unit-whitelist: Specify a whitelist of allowed property and unit pairs within declarations.
  #declaration-property-value-blacklist: Specify a blacklist of disallowed property and value pairs within declarations.
  #declaration-property-value-whitelist: Specify a whitelist of allowed property and value pairs within declarations.

  # Declaration block
  declaration-block-single-line-max-declarations: 1

  # Selector
  #selector-attribute-operator-blacklist: Specify a blacklist of disallowed attribute operators.
  #selector-attribute-operator-whitelist: Specify a whitelist of allowed attribute operators.
  #selector-class-pattern: Specify a pattern for class selectors.
  #selector-combinator-blacklist: Specify a blacklist of disallowed combinators.
  #selector-combinator-whitelist: Specify a whitelist of allowed combinators.
  #selector-id-pattern: Specify a pattern for ID selectors.
  #selector-max-attribute: Limit the number of attribute selectors in a selector.
  #selector-max-class: Limit the number of classes in a selector.
  #selector-max-combinators: Limit the number of combinators in a selector.
  #selector-max-compound-selectors: Limit the number of compound selectors in a selector.
  selector-max-empty-lines: 0
  #selector-max-id: Limit the number of ID selectors in a selector.
  #selector-max-pseudo-class: Limit the number of pseudo-classes in a selector.
  #selector-max-specificity: Limit the specificity of selectors.
  #selector-max-type: Limit the number of type in a selector.
  #selector-max-universal: Limit the number of universal selectors in a selector.
  #selector-nested-pattern: Specify a pattern for the selectors of rules nested within rules.
  #selector-no-qualifying-type: Disallow qualifying a selector by type.
  #selector-no-vendor-prefix: Disallow vendor prefixes for selectors.
  #selector-pseudo-class-blacklist: Specify a blacklist of disallowed pseudo-class selectors.
  #selector-pseudo-class-whitelist: Specify a whitelist of allowed pseudo-class selectors.
  #selector-pseudo-element-blacklist: Specify a blacklist of disallowed pseudo-element selectors.
  #selector-pseudo-element-whitelist: Specify a whitelist of allowed pseudo-element selectors.

  # Media feature
  #media-feature-name-blacklist: Specify a blacklist of disallowed media feature names.
  #media-feature-name-no-vendor-prefix: Disallow vendor prefixes for media feature names.
  #media-feature-name-value-whitelist: Specify a whitelist of allowed media feature name and value pairs.
  #media-feature-name-whitelist: Specify a whitelist of allowed media feature names.

  # Custom media
  #custom-media-pattern: Specify a pattern for custom media query names.

  # At-rule
  #at-rule-blacklist: Specify a blacklist of disallowed at-rules.
  #at-rule-no-vendor-prefix: Disallow vendor prefixes for at-rules.
  #at-rule-property-requirelist: Specify a requirelist of properties for an at-rule.
  #at-rule-whitelist: Specify a whitelist of allowed at-rules.

  # Comment
  #comment-word-blacklist: Specify a blacklist of disallowed words within comments.

  # General / Sheet
  #max-nesting-depth: Limit the depth of nesting.
  no-unknown-animations: true

  ## Stylistic Issues
  # Color
  color-hex-case: lower
  color-hex-length: short

  # Font family
  font-family-name-quotes: always-where-recommended

  # Font weight
  font-weight-notation: named-where-possible

  # Function
  function-comma-newline-after: never-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always-single-line
  function-comma-space-before: never
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: always-multi-line
  function-parentheses-space-inside: never
  function-url-quotes: never
  function-whitespace-after: always

  # Number
  number-leading-zero: always
  number-no-trailing-zeros: true

  # String
  string-quotes: double

  # Length
  length-zero-no-unit: true

  # Unit
  unit-case: lower

  # Value
  value-keyword-case: lower

  # Value list
  value-list-comma-newline-after: never-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  custom-property-empty-line-before: never

  # Property
  property-case: lower

  # Declaration
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-colon-newline-after: always-multi-line
  declaration-colon-space-after: always-single-line
  declaration-colon-space-before: never
  declaration-empty-line-before: never
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-trailing-semicolon: always

  # Block
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always
  block-closing-brace-newline-before: always
  block-closing-brace-space-after: never-single-line
  block-closing-brace-space-before: never-single-line
  block-opening-brace-newline-after: null
  block-opening-brace-newline-before: null
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always-single-line

  # Selector
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: always
  selector-attribute-operator-space-before: always
  selector-attribute-quotes: never
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-type-case: lower

  # Selector list
  selector-list-comma-newline-after: always-multi-line
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never

  # Rule
  rule-empty-line-before:
    - always
    - except:
        - after-single-line-comment
      ignore:
        - first-nested

  # Media feature
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always

  # Media query list
  media-query-list-comma-newline-after: always
  media-query-list-comma-newline-before: never-multi-line
  media-query-list-comma-space-after: always-single-line
  media-query-list-comma-space-before: never-single-line

  # At-rule
  at-rule-empty-line-before:
    - always
    - ignore:
        - after-comment
  at-rule-name-case: lower
  at-rule-name-newline-after: always-multi-line
  at-rule-name-space-after: always
  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never

  # Comment
  comment-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - stylelint-commands
  comment-whitespace-inside: always

  # General / Sheet
  indentation: 2
  linebreaks: unix
  max-empty-lines: 1
  #max-line-length: Limit the length of a line.
  no-eol-whitespace: true
  no-missing-end-of-source-newline: true
  no-empty-first-line: true
